/* ============================================================
   Definitions with animated explanations (5 per session)
   ============================================================ */
const ec = (cls, ...keys) => Object.fromEntries(keys.map(k => [k, cls]));
const nc = (cls, ...vs) => Object.fromEntries(vs.map(v => [v, cls]));
function simpleCopy(bg, max = 16) {
  if (!bg || !bg.nodes.length) return { error: 'The board has no graph.' }; if (bg.nodes.length > max) return { error: `Use a graph with at most ${max} vertices for this animation.` };
  const labels = bg.nodes.map((v, i) => (bg.parts > 1 ? v.label + (v.part ? '′' : '') : v.label));
  if (new Set(labels).size !== labels.length) return { error: 'Vertex names must be distinct.' };
  const g = newGraph(bg.directed); labels.forEach(l => addNode(g, '0|' + l, l)); bg.edges.forEach(e => g.edges.push({ u: e.u, v: e.v, w: e.w }));
  const pos = boardToCard({ nodes: bg.nodes.map((v, i) => ({ label: labels[i], x: v.x, y: v.y })) }); return { g, pos, labels };
}
const ekey = (g, e) => g.nodes[e.u].label + '-' + g.nodes[e.v].label;

/* --- shared random-graph data for session 10 cards (fixed seed) --- */
const RG = (() => { const r = rng(42); const L = 'abcdefghij'.split(''); const pairs = []; for (let i = 0; i < 10; i++) for (let j = i + 1; j < 10; j++) pairs.push([L[i], L[j], r()]); return { L, pairs }; })();
const rgText = RG.pairs.map(([a, b]) => `${a} ${b}`).join('\n');
const rgStep = (p, cap, colourComps) => {
  const e = {}; const on = RG.pairs.filter(x => x[2] < p); RG.pairs.forEach(([a, b, r]) => e[a + '-' + b] = r < p ? '' : 'hide');
  const n = {}; const par = Object.fromEntries(RG.L.map(l => [l, l])); const f = x => par[x] === x ? x : (par[x] = f(par[x])); on.forEach(([a, b]) => par[f(a)] = f(b));
  const sz = {}; RG.L.forEach(l => sz[f(l)] = (sz[f(l)] || 0) + 1); const big = Object.entries(sz).sort((x, y) => y[1] - x[1])[0][0];
  RG.L.forEach(l => { const deg = on.filter(([a, b]) => a === l || b === l).length; n[l] = colourComps ? (f(l) === big && sz[big] > 1 ? 'giant' : deg ? 'small' : 'iso') : (deg ? '' : 'iso'); });
  return [cap.replace('{m}', on.length), { e, n }];
};

const DEFS = {
  traverse: [
    { term: 'Walk, trail, path, cycle', text: 'A <b>walk</b> is a sequence v₀, e₁, v₁, …, eₖ, vₖ where each eᵢ joins vᵢ₋₁ and vᵢ. A <b>trail</b> repeats no edge, a <b>path</b> repeats no vertex, and a <b>cycle</b> is a closed trail whose only repeated vertex is the first = last (length ≥ 3).',
      g: 'A B\nB C\nC D\nD E\nE A\nB D', pos: ringPos(['A', 'B', 'C', 'D', 'E']),
      steps: [['A walk may repeat vertices and edges.', {}], ['Walk A–B–D–C–B–A: the vertex B and the edge A–B repeat.', { e: ec('path', 'A-B', 'B-D', 'D-C', 'C-B'), n: { A: 'cur', B: 'front' } }], ['Trail A–B–C–D–B: B repeats, but no edge does.', { reset: true, e: ec('tree', 'A-B', 'B-C', 'C-D', 'D-B'), n: { B: 'front' } }], ['Path A–B–C–D: nothing repeats.', { reset: true, e: ec('tree', 'A-B', 'B-C', 'C-D'), n: { A: 'cur', D: 'cur' } }], ['Cycle B–C–D–B: a path closed up by one more edge.', { reset: true, e: ec('cut', 'B-C', 'C-D', 'D-B') }]] },
    { term: 'Distance and BFS layers', text: 'The <b>distance</b> d(u, v) is the number of edges on a shortest u–v path. Breadth-first search from s finds the <b>layers</b> Lᵢ = {v : d(s, v) = i} in order.',
      g: 'S A\nS B\nA C\nB C\nB D\nC E\nD E', pos: { S: [32, 97], A: [100, 45], B: [100, 150], C: [180, 55], D: [180, 150], E: [262, 100] },
      steps: [['Start: d(S) = 0.', { n: { S: 'cur' }, t: { S: '0' } }], ['Layer 1: the neighbours of S.', { n: { S: 'done', A: 'front', B: 'front' }, t: { A: '1', B: '1' }, e: ec('tree', 'S-A', 'S-B') }], ['Layer 2: new neighbours of layer 1.', { n: { A: 'done', B: 'done', C: 'front', D: 'front' }, t: { C: '2', D: '2' }, e: ec('tree', 'A-C', 'B-D') }], ['Layer 3. The non-tree edge B–C joins consecutive layers.', { n: { C: 'done', D: 'done', E: 'front' }, t: { E: '3' }, e: Object.assign(ec('tree', 'C-E'), ec('back', 'B-C')) }]],
      gen(bg) { const c = simpleCopy(bg); if (c.error) return c; const g = c.g, n = g.nodes.length, A = adjOut(g), d = Array(n).fill(-1), par = Array(n).fill(-1); d[0] = 0; const Q = [0]; for (let h = 0; h < Q.length; h++) for (const { to, e } of A[Q[h]]) if (d[to] < 0) { d[to] = d[Q[h]] + 1; par[to] = e; Q.push(to); }
        const steps = []; const mx = Math.max(...d); const st = { n: {}, t: {}, e: {} };
        for (let k = 0; k <= mx; k++) { const L = g.nodes.map((v, i) => i).filter(i => d[i] === k); const s = { n: {}, t: {}, e: {} }; g.nodes.forEach((v, i) => { if (d[i] >= 0 && d[i] < k) s.n[v.label] = 'done'; }); L.forEach(i => { s.n[g.nodes[i].label] = k ? 'front' : 'cur'; s.t[g.nodes[i].label] = String(k); if (par[i] >= 0) s.e[ekey(g, g.edges[par[i]])] = 'tree'; }); steps.push([`Layer ${k}: ${L.map(i => esc(g.nodes[i].label)).join(', ')}.`, s]); }
        return { g, pos: c.pos, steps }; } },
    { term: 'Eccentricity, radius, diameter', text: 'ecc(v) = max over u of d(v, u). The <b>radius</b> is the least eccentricity, the <b>diameter</b> the greatest; the <b>centre</b> consists of the vertices of eccentricity equal to the radius. Always rad ≤ diam ≤ 2·rad.',
      g: 'a b\nb c\nc d\nd e\nc f', pos: Object.assign(rowPos(['a', 'b', 'c', 'd', 'e'], 70), { f: [150, 155] }),
      steps: [['ecc(v): the distance to the farthest vertex.', { t: { a: '4', b: '3', c: '2', d: '3', e: '4', f: '3' } }], ['Radius = 2, attained only at c: the centre.', { n: { c: 'cur' } }], ['Diameter = 4: a and e are farthest apart.', { n: { a: 'cut', e: 'cut' }, e: ec('cut', 'a-b', 'b-c', 'c-d', 'd-e') }], ['Here diam = 2·rad: the upper bound is attained.', {}]] },
    { term: 'Bipartite graphs and odd cycles', text: 'G is <b>bipartite</b> if V splits into X and Y with every edge joining X to Y. <b>König:</b> G is bipartite exactly when it contains no odd cycle.',
      g: 'a b\nb c\nc d\nd e\ne f\nf a\na c', pos: ringPos(['a', 'b', 'c', 'd', 'e', 'f']),
      steps: [['Two sides; every edge of the 6-cycle crosses.', { n: Object.assign(nc('k0', 'a', 'c', 'e'), nc('k1', 'b', 'd', 'f')), e: { 'a-c': 'hide' } }], ['An even cycle alternates sides without trouble.', { e: ec('tree', 'a-b', 'b-c', 'c-d', 'd-e', 'e-f', 'f-a') }], ['Add the chord a–c: it joins two vertices of one side.', { e: { 'a-c': 'cut' }, n: nc('cut', 'a', 'c') }], ['a–b–c–a is an odd cycle, so no 2-colouring exists.', { e: Object.assign(ec('', 'c-d', 'd-e', 'e-f', 'f-a'), ec('cut', 'a-b', 'b-c')) }]] },
    { term: 'DAG and topological order', text: 'A <b>topological order</b> lists the vertices so that every arc u→v has u before v. It exists exactly when the digraph has no directed cycle (a DAG); reversed DFS finishing times give one.',
      g: 'directed\na c\nb c\nc e\nb d\nd e\ne f', pos: { a: [60, 40], b: [55, 150], c: [140, 85], d: [150, 165], e: [220, 115], f: [268, 40] },
      steps: [['A directed acyclic graph: no arc leads back.', {}], ['One valid order: a, b, c, d, e, f.', { t: { a: '1', b: '2', c: '3', d: '4', e: '5', f: '6' } }], ['Line the vertices up in that order: every arc points right.', { p: { a: [30, 70], b: [78, 130], c: [126, 70], d: [174, 130], e: [222, 70], f: [270, 130] } }], ['A directed cycle would need an arc pointing left.', { e: ec('tree', 'a-c', 'b-c', 'c-e', 'b-d', 'd-e', 'e-f') }]] },
  ],
  degrees: [
    { term: 'Degree and the handshake lemma', text: 'deg(v) counts the edges at v. <b>Handshake lemma:</b> Σ deg(v) = 2m. Hence every graph has an even number of vertices of odd degree.',
      g: 'a b\na c\na d\nb c\nc e', pos: { a: [110, 60], b: [55, 150], c: [165, 145], d: [175, 35], e: [260, 145] },
      steps: [['Degrees: 3, 2, 3, 1, 1.', { t: { a: '3', b: '2', c: '3', d: '1', e: '1' } }], ['Each edge has two ends: it adds 2 to the sum.', { e: { 'a-b': 'path' }, n: nc('front', 'a', 'b') }], ['Σ deg = 10 = 2·5 = 2m.', { e: ec('tree', 'a-b', 'a-c', 'a-d', 'b-c', 'c-e'), n: nc('', 'a', 'b') }], ['Odd-degree vertices: a, c, d, e. Always an even number.', { n: nc('cut', 'a', 'c', 'd', 'e') }]],
      gen(bg) { const c = simpleCopy(bg); if (c.error) return c; const g = c.g; const deg = g.nodes.map(() => 0); g.edges.forEach(e => { deg[e.u]++; deg[e.v]++; }); const t = {}; g.nodes.forEach((v, i) => t[v.label] = String(deg[i])); const odd = g.nodes.filter((v, i) => deg[i] % 2).map(v => v.label);
        return { g, pos: c.pos, steps: [['Degrees of the board’s graph.', { t }], [`Σ deg = ${deg.reduce((a, b) => a + b, 0)} = 2·${g.edges.length}.`, { e: Object.fromEntries(g.edges.map(e => [ekey(g, e), 'tree'])) }], [`${odd.length} odd-degree vertices: an even number.`, { n: nc('cut', ...odd) }]] }; } },
    { term: 'Graphical sequences', text: 'A sequence d₁ ≥ … ≥ dₙ is <b>graphical</b> if some simple graph has these degrees. Many non-isomorphic graphs can share one degree sequence.',
      g: 'a b\nb c\nc d\nd e\ne f\nf a\nc a\nf d', pos: ringPos(['a', 'b', 'c', 'd', 'e', 'f']),
      steps: [['(2, 2, 2, 2, 2, 2) is graphical: the 6-cycle realises it.', { e: { 'c-a': 'hide', 'f-d': 'hide' }, t: { a: '2', b: '2', c: '2', d: '2', e: '2', f: '2' } }], ['Swap c–d, f–a for c–a, f–d.', { e: Object.assign(ec('rej', 'c-d', 'f-a'), ec('hl', 'c-a', 'f-d')) }], ['Two triangles: the same degrees, a different graph.', { e: Object.assign(ec('hide', 'c-d', 'f-a'), ec('', 'c-a', 'f-d')) }], ['The degree sequence does not determine the graph.', {}]] },
    { term: 'Havel–Hakimi', text: '(d₁, …, dₙ) with d₁ largest is graphical iff the sequence obtained by deleting d₁ and subtracting 1 from the next d₁ largest terms is graphical.',
      g: 'a b\na c\na d\nb e\nb c\ne d', pos: ringPos(['a', 'b', 'c', 'd', 'e']),
      steps: [['(3, 3, 2, 2, 2). Take a, which has the largest degree 3.', { e: ec('hide', 'a-b', 'a-c', 'a-d', 'b-e', 'b-c', 'e-d'), t: { a: '3', b: '3', c: '2', d: '2', e: '2' }, n: { a: 'cur' } }], ['Join a to the next three: b, c, d. Subtract 1 from each.', { e: ec('hl', 'a-b', 'a-c', 'a-d'), t: { a: '0', b: '2', c: '1', d: '1' }, n: Object.assign({ a: 'done' }, nc('front', 'b', 'c', 'd')) }], ['Now (2, 2, 1, 1) on b, e, c, d. Join b to e and c.', { e: Object.assign(ec('tree', 'a-b', 'a-c', 'a-d'), ec('hl', 'b-e', 'b-c')), t: { b: '0', e: '1', c: '0' }, n: Object.assign(nc('done', 'b', 'c'), nc('front', 'e', 'd')) }], ['Join e and d. All residuals are 0: graphical.', { e: ec('tree', 'b-e', 'b-c', 'e-d'), t: { e: '0', d: '0' }, n: nc('done', 'e', 'd') }]] },
    { term: 'Cut vertex and bridge', text: 'A <b>cut vertex</b> (<b>bridge</b>) is a vertex (edge) whose deletion increases the number of components. An edge is a bridge exactly when it lies on no cycle.',
      g: 'a b\nb c\nc a\nc d\nd e\ne f\nf d', pos: { a: [38, 45], b: [38, 150], c: [110, 97], d: [190, 97], e: [262, 45], f: [262, 150] },
      steps: [['Two triangles joined by one edge.', {}], ['c–d lies on no cycle.', { e: { 'c-d': 'cut' } }], ['Delete it: two components remain. c–d is a bridge.', { e: { 'c-d': 'hide' }, n: Object.assign(nc('k0', 'a', 'b', 'c'), nc('k1', 'd', 'e', 'f')) }], ['c and d are cut vertices as well.', { e: { 'c-d': '' }, n: Object.assign(nc('', 'a', 'b', 'e', 'f'), nc('cut', 'c', 'd')) }]] },
    { term: 'Connectivity κ ≤ λ ≤ δ', text: 'κ(G) and λ(G) are the least numbers of vertices and of edges whose removal disconnects G. <b>Whitney:</b> κ(G) ≤ λ(G) ≤ δ(G).',
      g: 'a b\nb c\nc a\nc d\nd e\ne c', pos: { a: [45, 45], b: [45, 150], c: [150, 97], d: [255, 45], e: [255, 150] },
      steps: [['A bow tie: two triangles sharing c.', {}], ['Remove c: two pieces. κ = 1.', { n: { c: 'cut' } }], ['No single edge disconnects it; removing c–a and c–b does. λ = 2.', { n: { c: '' }, e: ec('cut', 'c-a', 'b-c') }], ['Minimum degree δ = 2. Here 1 ≤ 2 ≤ 2.', { e: ec('', 'c-a', 'b-c'), t: { a: '2', b: '2', c: '4', d: '2', e: '2' } }]] },
  ],
  iso: [
    { term: 'Isomorphism', text: 'G ≅ H if there is a bijection f : V(G) → V(H) with uv ∈ E(G) ⇔ f(u)f(v) ∈ E(H). A drawing is not part of the graph.',
      g: 'a b\nb c\nc d\nd e\ne a', pos: ringPos(['a', 'b', 'c', 'd', 'e']),
      steps: [['A 5-cycle drawn as a pentagon.', {}], ['Move the vertices: the same edges now form a pentagram.', { p: ringPos(['a', 'c', 'e', 'b', 'd']) }], ['Same vertices, same adjacencies: the same graph.', { e: ec('tree', 'a-b', 'b-c', 'c-d', 'd-e', 'e-a') }], ['And back. Isomorphic graphs differ only in names and drawing.', { p: ringPos(['a', 'b', 'c', 'd', 'e']), e: ec('', 'a-b', 'b-c', 'c-d', 'd-e', 'e-a') }]] },
    { term: 'Invariants', text: 'An <b>invariant</b> takes equal values on isomorphic graphs (order, size, degree sequence, number of triangles, χ, …). A differing value proves non-isomorphism; equal values prove nothing.',
      g: 'a b\nb c\nc d\nd e\ne f\nf a\nu v\nv w\nw u\nx y\ny z\nz x', pos: Object.assign(ringPos(['a', 'b', 'c', 'd', 'e', 'f'], 78, 97, 55), ringPos(['u', 'v', 'w'], 205, 55, 30), ringPos(['x', 'y', 'z'], 245, 140, 30)),
      steps: [['Both: 6 vertices, 6 edges, every degree 2.', { t: Object.fromEntries('abcdefuvwxyz'.split('').map(l => [l, '2'])) }], ['Count triangles: none on the left…', { t: {} }], ['…two on the right.', { e: ec('cut', 'u-v', 'v-w', 'w-u', 'x-y', 'y-z', 'z-x') }], ['A differing invariant: not isomorphic.', {}]] },
    { term: 'Colour refinement (1-WL)', text: 'Repeatedly replace each vertex colour by (colour, multiset of neighbour colours), renaming the pairs by new colours, until no class splits. Different colour histograms prove non-isomorphism.',
      g: 'a b\nb c\nc d\nd e', pos: rowPos(['a', 'b', 'c', 'd', 'e']),
      steps: [['Round 0: every vertex looks the same.', { n: nc('k0', 'a', 'b', 'c', 'd', 'e') }], ['Round 1: neighbour multisets separate the degrees.', { n: Object.assign(nc('k1', 'a', 'e'), nc('k2', 'b', 'c', 'd')) }], ['Round 2: b and d see an end vertex; c does not.', { n: Object.assign(nc('k3', 'b', 'd'), nc('k4', 'c')) }], ['Stable. Equal colours do not guarantee a symmetry in general.', {}]] },
    { term: 'Automorphism and orbit', text: 'An <b>automorphism</b> is an isomorphism G → G. The <b>orbit</b> of v is {σ(v) : σ ∈ Aut(G)}. Vertices in one orbit are structurally indistinguishable.',
      g: 'a b\nb c\nc d\nd a', pos: ringPos(['a', 'b', 'c', 'd'], 150, 97, 62, -135),
      steps: [['The 4-cycle.', {}], ['Rotate a quarter turn: a→b→c→d→a. Edges go to edges.', { p: (() => { const P = ringPos(['a', 'b', 'c', 'd'], 150, 97, 62, -135); return { a: P.b, b: P.c, c: P.d, d: P.a }; })() }], ['Any vertex can be moved to any other: one orbit.', { n: nc('k0', 'a', 'b', 'c', 'd') }], ['|Aut(C₄)| = 8: four rotations and four reflections.', {}]] },
    { term: 'Fixing set', text: 'S ⊆ V is a <b>fixing set</b> if the identity is the only automorphism fixing every vertex of S. The fixing number is the size of a smallest one.',
      g: 'a b\nb c\nc d\nd e\ne f\nf a', pos: ringPos(['a', 'b', 'c', 'd', 'e', 'f']),
      steps: [['|Aut(C₆)| = 12.', {}], ['Fix a: one non-trivial symmetry remains, the mirror through a.', { n: { a: 'cur' }, t: { a: 'fixed' } }], ['It swaps b ↔ f and c ↔ e.', { n: Object.assign(nc('k1', 'b', 'f'), nc('k2', 'c', 'e')) }], ['Fix b too: only the identity fixes {a, b}. Fixing number 2.', { n: Object.assign({ b: 'cur' }, nc('', 'f', 'c', 'e')), t: { b: 'fixed' } }]] },
  ],
  mst: [
    { term: 'Tree', text: 'A <b>tree</b> is a connected acyclic graph. Equivalently: connected with n − 1 edges; acyclic with n − 1 edges; exactly one path between any two vertices.',
      g: 'a b\nb c\nb d\nd e\nd f\nc e', pos: { a: [40, 97], b: [110, 97], c: [170, 40], d: [170, 150], e: [250, 95], f: [250, 165] },
      steps: [['Connected and acyclic: 6 vertices, 5 edges.', { e: { 'c-e': 'hide' } }], ['Add any edge, here c–e…', { e: { 'c-e': 'hl' } }], ['…and exactly one cycle appears.', { e: ec('cut', 'c-e', 'b-c', 'b-d', 'd-e') }], ['Delete any edge of that cycle: a tree again.', { e: Object.assign(ec('', 'c-e', 'b-c', 'd-e'), { 'b-d': 'hide' }) }]] },
    { term: 'Spanning tree', text: 'A <b>spanning tree</b> of a connected graph is a subgraph that is a tree and contains every vertex. Kₙ has nⁿ⁻² of them (Cayley).',
      g: 'a b\nb c\nc d\nd a\na c\nb d', pos: ringPos(['a', 'b', 'c', 'd'], 150, 97, 66, -135),
      steps: [['K₄.', {}], ['One spanning tree: the star at a.', { e: ec('tree', 'a-b', 'a-c', 'd-a') }], ['Another: the path a–b–c–d.', { e: Object.assign(ec('', 'a-c', 'd-a'), ec('tree', 'a-b', 'b-c', 'c-d')) }], ['K₄ has 4² = 16 spanning trees.', {}]],
      gen(bg) { const c = simpleCopy(bg); if (c.error) return c; const g = c.g, n = g.nodes.length, A = adjUnd(g), seen = Array(n).fill(false), te = []; seen[0] = true; const Q = [0]; for (let h = 0; h < Q.length; h++) for (const { to, e } of A[Q[h]]) if (!seen[to]) { seen[to] = true; te.push(e); Q.push(to); }
        if (te.length !== n - 1) return { error: 'The board’s graph is disconnected, so it has no spanning tree.' };
        const steps = [['The board’s graph.', {}]]; const st = {}; for (let k = 0; k < te.length; k += Math.ceil(te.length / 3)) { te.slice(k, k + Math.ceil(te.length / 3)).forEach(e => st[ekey(g, g.edges[e])] = 'tree'); steps.push([`BFS tree: ${Object.keys(st).length} of ${n - 1} edges.`, { e: { ...st } }]); }
        steps.push([`A spanning tree: ${n} vertices, ${n - 1} edges.`, {}]); return { g, pos: c.pos, steps }; } },
    { term: 'Cut property', text: 'For any cut (S, V ∖ S), a lightest edge crossing it belongs to some minimum spanning tree. Kruskal and Prim add only such edges.',
      g: 'a b 4\na c 2\nb c 5\nb d 7\nc d 3\nc e 8\nd e 1', pos: { a: [40, 60], b: [90, 160], c: [130, 60], d: [210, 150], e: [265, 60] }, weights: true,
      steps: [['A cut: S = {a, b, c} against the rest.', { blob: [[['a', 'b', 'c'], 'sA']] }], ['Three edges cross it.', { e: ec('cand', 'b-d', 'c-d', 'c-e') }], ['The lightest, c–d (3), is in some MST.', { e: { 'c-d': 'tree', 'b-d': 'cand', 'c-e': 'cand' } }], ['If a tree used b–d (7) instead, swapping in c–d would save 4.', { e: { 'b-d': 'cut' } }]] },
    { term: 'Cycle property', text: 'If e is the unique heaviest edge on some cycle, no minimum spanning tree contains e. A spanning tree is minimum iff every non-tree edge is a heaviest edge on the cycle it closes.',
      g: 'a b 4\na c 2\nb c 5\nb d 7\nc d 3\nc e 8\nd e 1', pos: { a: [40, 60], b: [90, 160], c: [130, 60], d: [210, 150], e: [265, 60] }, weights: true,
      steps: [['The cycle a–b–c–a.', { e: ec('cand', 'a-b', 'b-c', 'a-c') }], ['Its heaviest edge b–c (5) is in no MST.', { e: { 'b-c': 'cut' } }], ['Kruskal reaches b–c after a–c and a–b: b and c are already joined.', { e: Object.assign(ec('tree', 'a-b', 'a-c'), { 'b-c': 'rej' }) }], ['The cycle property certifies minimality edge by edge.', {}]] },
    { term: 'Union–find', text: 'Disjoint sets are stored as rooted trees. FIND follows parent pointers to the root; UNION links two roots. With union by rank and path compression, each operation costs O(α(n)).',
      g: 'directed\nb a\nc a\nd c\nf e\nd a', pos: { a: [80, 40], b: [35, 120], c: [125, 110], d: [170, 170], e: [225, 50], f: [255, 140] },
      steps: [['MAKE-SET: six singletons.', { n: { a: 'k0', b: 'k1', c: 'k2', d: 'k3', e: 'k4', f: 'k5' }, e: ec('hide', 'b-a', 'c-a', 'd-c', 'f-e', 'd-a') }], ['UNION(a, b), UNION(a, c): b and c point to the root a.', { n: nc('k0', 'b', 'c'), e: ec('tree', 'b-a', 'c-a') }], ['UNION(c, d) hangs d below c; UNION(e, f).', { n: { d: 'k0', f: 'k4' }, e: ec('tree', 'd-c', 'f-e') }], ['FIND(d) walks d → c → a; path compression points d straight at a.', { n: { d: 'cur' }, e: { 'd-c': 'hide', 'd-a': 'tree' } }]] },
  ],
  sp: [
    { term: 'Weighted distance', text: 'The length of a path is the sum of its edge weights; d(s, v) is the least length of an s–v path (∞ if there is none, undefined if a negative cycle is reachable).',
      g: 'directed\ns a 4\ns b 1\nb a 2\na t 1\nb t 5', pos: { s: [35, 97], a: [150, 40], b: [150, 155], t: [265, 97] }, weights: true,
      steps: [['Find the shortest route from s to t.', { n: { s: 'cur', t: 'front' } }], ['s → a directly costs 4…', { e: { 's-a': 'path' } }], ['…but s → b → a costs 3. Fewer edges is not shorter.', { e: { 's-a': '', 's-b': 'path', 'b-a': 'path' } }], ['d(s, t) = 4 along s → b → a → t.', { e: { 'a-t': 'path' }, t: { t: 'd = 4' } }]] },
    { term: 'Relaxation', text: 'Relaxing (u, v): if d(u) + w(u, v) < d(v), set d(v) ← d(u) + w(u, v) and π(v) ← u. Labels only decrease and never drop below the true distance.',
      g: 'directed\ns u 3\ns v 7\nu v 2', pos: { s: [40, 97], u: [150, 40], v: [260, 120] }, weights: true,
      steps: [['Current labels: d(u) = 3, d(v) = 7.', { t: { s: '0', u: '3', v: '7' }, e: ec('tree', 's-u', 's-v') }], ['Relax u → v: 3 + 2 = 5 < 7.', { e: { 'u-v': 'cand' }, n: { u: 'cur' } }], ['Improve: d(v) ← 5, predecessor u.', { t: { v: '5' }, e: { 'u-v': 'tree', 's-v': '' }, n: { u: '', v: 'front' } }], ['Dijkstra, Bellman–Ford and A* are schedules of relaxations.', {}]] },
    { term: 'Shortest-path tree', text: 'The predecessor edges form a shortest-path tree. Labels are correct exactly when d(s) = 0, every edge satisfies d(v) ≤ d(u) + w(u, v), and each d(v) is realised by a tree path.',
      g: 'directed\nS A 2\nS B 6\nA B 1\nA C 4\nB C 1\nB T 7\nC T 2', pos: { S: [30, 97], A: [100, 40], B: [130, 150], C: [200, 60], T: [270, 130] }, weights: true,
      steps: [['Distances from S.', { t: { S: '0', A: '2', B: '3', C: '4', T: '6' } }], ['The predecessor edges form a tree.', { e: ec('tree', 'S-A', 'A-B', 'B-C', 'C-T') }], ['Check a non-tree edge, B → T: 6 ≤ 3 + 7.', { e: { 'B-T': 'cand' } }], ['Every edge passes: the labels are certified.', { e: { 'B-T': '' } }]] },
    { term: 'Negative cycle', text: 'A cycle of negative total weight. If one is reachable from s, distances are undefined (−∞). Bellman–Ford detects it when an n-th pass still relaxes some edge.',
      g: 'directed\ns a 1\na b 1\nb c -3\nc a 1', pos: { s: [35, 97], a: [130, 97], b: [215, 40], c: [215, 155] }, weights: true,
      steps: [['a → b → c → a weighs 1 − 3 + 1 = −1.', { e: ec('cut', 'a-b', 'b-c', 'c-a'), t: { a: '1' } }], ['One lap later: d(a) = 0.', { t: { a: '0' } }], ['Another: d(a) = −1, and so on.', { t: { a: '−1' } }], ['No shortest walk exists: d(a) = −∞.', { t: { a: '−∞' } }]] },
    { term: 'Admissible heuristic (A*)', text: 'A* settles vertices by f(v) = g(v) + h(v). If h never overestimates the remaining distance (admissible) and is consistent, the first label A* settles at the target is optimal.',
      g: 's a 3\na t 3\ns b 2\nb c 2\nc t 4', pos: { s: [30, 140], a: [150, 40], t: [270, 140], b: [100, 170], c: [200, 170] }, weights: true,
      steps: [['Find s → t. The heuristic is straight-line distance to t.', { n: { s: 'cur', t: 'front' } }], ['h values: farther from t means larger h.', { t: { s: 'h=6', a: 'h=4', b: 'h=4', c: 'h=2' } }], ['f = g + h steers the search toward t.', { e: ec('path', 's-a', 'a-t') }], ['With h ≡ 0, A* is exactly Dijkstra.', {}]] },
  ],
  route: [
    { term: 'Euler circuit', text: 'An <b>Euler circuit</b> uses every edge exactly once and returns to its start. A connected graph has one iff every vertex has even degree.',
      g: 'c a\na b\nb c\nc d\nd e\ne c', pos: { a: [45, 45], b: [45, 150], c: [150, 97], d: [255, 45], e: [255, 150] },
      steps: [['All degrees are even (2, 2, 4, 2, 2).', { t: { a: '2', b: '2', c: '4', d: '2', e: '2' } }], ['Start at c: c → a → b → c.', { e: ec('tree', 'c-a', 'a-b', 'b-c'), el: { 'c-a': '1', 'a-b': '2', 'b-c': '3' } }], ['Continue c → d → e → c.', { e: ec('tree', 'c-d', 'd-e', 'e-c'), el: { 'c-d': '4', 'd-e': '5', 'e-c': '6' } }], ['Each edge once, back at c.', {}]] },
    { term: 'Odd vertices and the postman', text: '<b>Chinese postman:</b> the cheapest closed walk covering every edge. Add, as cheaply as possible, paths pairing up the odd-degree vertices; then take an Euler circuit.',
      g: 'a b 1\nb c 1\nc d 1\nd a 1\na c 2\nb d 2', pos: ringPos(['a', 'b', 'c', 'd'], 150, 97, 66, -135), weights: true,
      steps: [['Every vertex has degree 3: no Euler circuit.', { n: nc('cut', 'a', 'b', 'c', 'd'), t: { a: '3', b: '3', c: '3', d: '3' } }], ['Pair the odd vertices: a–b and c–d, cost 1 + 1.', { e: ec('path', 'a-b', 'c-d') }], ['Walk those edges twice: all degrees even.', { e: ec('dup', 'a-b', 'c-d'), n: nc('', 'a', 'b', 'c', 'd'), t: { a: '4', b: '4', c: '4', d: '4' } }], ['Tour length = 8 + 2 = 10.', {}]] },
    { term: 'Hamilton cycle', text: 'A <b>Hamilton cycle</b> visits every vertex exactly once. Deciding whether one exists is NP-complete: a found cycle is easy to check, but “no” has no known short proof.',
      g: cubeText, pos: { '000': [70, 165], '001': [230, 165], '010': [70, 30], '011': [230, 30], '100': [115, 125], '101': [185, 125], '110': [115, 70], '111': [185, 70] },
      steps: [['The cube Q₃.', {}], ['000 → 001 → 011 → 010…', { e: ec('tree', '000-001', '001-011', '010-011') }], ['…→ 110 → 111 → 101 → 100…', { e: ec('tree', '010-110', '110-111', '101-111', '100-101') }], ['…→ 000. Every vertex once.', { e: { '000-100': 'tree' } }]] },
    { term: 'Triangle inequality and shortcuts', text: 'Metric TSP assumes d(a, c) ≤ d(a, b) + d(b, c). Shortest-path distances always satisfy it, so skipping an already visited vertex never lengthens a tour.',
      g: 'a b 3\nb c 4\na c 5', pos: { a: [40, 160], b: [150, 40], c: [260, 160] }, weights: true,
      steps: [['d(a, c) = 5 ≤ 3 + 4.', {}], ['A walk a → b → c that already visited b…', { e: ec('path', 'a-b', 'b-c') }], ['…can go straight from a to c instead.', { e: Object.assign(ec('', 'a-b', 'b-c'), { 'a-c': 'tree' }) }], ['This is why the double-tree and Christofides guarantees hold.', {}]] },
    { term: 'Subtour elimination', text: 'TSP as an ILP: x(e) ∈ {0, 1}, Σ x(e) = 2 at every vertex, and Σ x(e) ≥ 2 over the edges leaving every proper subset S. The last family forbids disjoint subtours.',
      g: 'a b\nb c\nc a\nd e\ne f\nf d\nc d\nb e\na f', pos: { a: [50, 45], b: [50, 150], c: [120, 97], d: [180, 97], e: [250, 150], f: [250, 45] },
      steps: [['Degree constraints only: two edges at every vertex.', {}], ['Two triangles satisfy them, but this is no tour.', { e: ec('tree', 'a-b', 'b-c', 'c-a', 'd-e', 'e-f', 'f-d') }], ['The constraint for S = {a, b, c}: at least 2 chosen edges must leave S.', { blob: [[['a', 'b', 'c'], 'sA']], e: ec('cand', 'c-d', 'b-e', 'a-f') }], ['A tour: a–b–c–d–e–f–a.', { blob: [], e: Object.assign(ec('', 'c-a', 'f-d', 'b-e'), ec('tree', 'a-b', 'b-c', 'c-d', 'd-e', 'e-f', 'a-f')) }]] },
  ],
  flow: [
    { term: 'Flow network and flow', text: 'A flow f satisfies 0 ≤ f(e) ≤ c(e) on each arc and <b>conservation</b> (in = out) at every vertex other than s and t. Its value |f| is the net flow leaving s.',
      g: 'directed\ns a 3\ns b 2\na b 1\na t 2\nb t 3', pos: { s: [35, 97], a: [150, 40], b: [150, 155], t: [265, 97] }, weights: true,
      steps: [['Arcs with capacities; source s, sink t.', { n: { s: 'cur', t: 'front' } }], ['A flow: 0 ≤ f ≤ c on every arc.', { el: { 's-a': '2/3', 's-b': '2/2', 'a-b': '0/1', 'a-t': '2/2', 'b-t': '2/3' }, e: ec('flow', 's-a', 's-b', 'a-t', 'b-t') }], ['Conservation at a: 2 in, 2 out.', { blob: [[['a'], 'sB']] }], ['|f| = 4 leaves s and reaches t.', { blob: [] }]] },
    { term: 'Residual network', text: 'For a flow f, the residual network G_f has an arc u→v of capacity c(u, v) − f(u, v) when positive, and a reverse arc v→u of capacity f(u, v) when positive.',
      g: 'directed\nu v 5\nv u 3', pos: { u: [60, 97], v: [240, 97] },
      steps: [['An arc of capacity 5 carrying 3 units.', { e: { 'v-u': 'hide' }, el: { 'u-v': '3/5' }, n: {} }], ['Forward residual: 5 − 3 = 2 more units can go u → v.', { el: { 'u-v': '2' }, e: { 'u-v': 'res' } }], ['Backward residual: the 3 units can be sent back.', { e: { 'v-u': 'resb' }, el: { 'v-u': '3' } }], ['Augmenting paths may use either kind of arc.', {}]] },
    { term: 'Augmenting path', text: 'An <b>augmenting path</b> is an s–t path in G_f. Pushing its bottleneck increases |f|; f is maximum exactly when no augmenting path exists.',
      g: 'directed\ns a 3\ns b 2\na b 1\na t 2\nb t 3', pos: { s: [35, 97], a: [150, 40], b: [150, 155], t: [265, 97] },
      steps: [['Zero flow.', { el: { 's-a': '0/3', 's-b': '0/2', 'a-b': '0/1', 'a-t': '0/2', 'b-t': '0/3' } }], ['Path s → a → t, bottleneck 2.', { e: ec('path', 's-a', 'a-t'), el: { 's-a': '2/3', 'a-t': '2/2' } }], ['Path s → b → t, bottleneck 2.', { e: Object.assign(ec('flow', 's-a', 'a-t'), ec('path', 's-b', 'b-t')), el: { 's-b': '2/2', 'b-t': '2/3' } }], ['Path s → a → b → t, bottleneck 1. |f| = 5.', { e: Object.assign(ec('flow', 's-b'), ec('path', 's-a', 'a-b', 'b-t')), el: { 's-a': '3/3', 'a-b': '1/1', 'b-t': '3/3' } }]] },
    { term: 's–t cut', text: 'An s–t cut (S, T) has capacity Σ c(u, v) over arcs from S to T. Every flow satisfies |f| ≤ c(S, T). <b>Max-flow min-cut:</b> the largest flow value equals the smallest cut capacity.',
      g: 'directed\ns a 3\ns b 2\na b 1\na t 2\nb t 3', pos: { s: [35, 97], a: [150, 40], b: [150, 155], t: [265, 97] }, weights: true,
      steps: [['S = {s, a}, T = {b, t}.', { blob: [[['s', 'a'], 'sA']] }], ['Arcs from S to T: 2 + 1 + 2 = 5.', { e: ec('cut', 's-b', 'a-b', 'a-t') }], ['Every unit of flow crosses the cut: |f| ≤ 5.', {}], ['A flow of value 5 exists, so both are optimal.', { el: { 's-a': '3/3', 's-b': '2/2', 'a-b': '1/1', 'a-t': '2/2', 'b-t': '3/3' } }]] },
    { term: 'Menger’s theorem', text: 'The maximum number of edge-disjoint s–t paths equals the minimum number of edges whose removal separates s from t (max-flow min-cut with unit capacities).',
      g: 's a\ns b\na c\nb c\na t\nc t\nb d\nd t', pos: { s: [35, 97], a: [120, 40], b: [120, 155], c: [180, 97], d: [200, 165], t: [265, 97] },
      steps: [['How many edge-disjoint routes from s to t?', { n: { s: 'cur', t: 'front' } }], ['Route 1: s–a–t.', { e: ec('tree', 's-a', 'a-t') }], ['Route 2: s–b–d–t.', { e: ec('path', 's-b', 'b-d', 'd-t') }], ['s has only 2 edges, a cut of size 2: so 2 is the maximum.', { e: ec('cut', 's-a', 's-b') }]] },
  ],
  match: [
    { term: 'Matching: maximal vs maximum', text: 'A <b>matching</b> is a set of pairwise disjoint edges. Maximal: no edge can be added. Maximum: largest possible size ν(G). Maximum implies maximal, not conversely.',
      g: 'a b\nb c\nc d', pos: rowPos(['a', 'b', 'c', 'd']),
      steps: [['The path a–b–c–d.', {}], ['{b–c} is maximal: every other edge touches it.', { e: { 'b-c': 'match' } }], ['…but {a–b, c–d} is larger.', { e: { 'b-c': '', 'a-b': 'match', 'c-d': 'match' } }], ['ν = 2.', {}]] },
    { term: 'Augmenting path', text: 'An M-<b>augmenting path</b> alternates between edges outside and inside M and joins two unmatched vertices. <b>Berge:</b> M is maximum iff no augmenting path exists.',
      g: 'a b\nb c\nc d', pos: rowPos(['a', 'b', 'c', 'd']),
      steps: [['M = {b–c}; a and d are unmatched.', { e: { 'b-c': 'match' }, n: nc('cut', 'a', 'd') }], ['a–b–c–d alternates: out, in, out.', { e: ec('path', 'a-b', 'c-d') }], ['Flip it: in and out swap.', { e: Object.assign(ec('match', 'a-b', 'c-d'), { 'b-c': '' }), n: nc('', 'a', 'd') }], ['|M| grew by one.', {}]] },
    { term: 'Vertex cover and König', text: 'A <b>vertex cover</b> meets every edge; τ(G) is its minimum size. Always ν(G) ≤ τ(G). <b>König:</b> equality holds in bipartite graphs.',
      g: 'x1 y1\nx1 y2\nx2 y1\nx3 y2\nx3 y3', pos: colsPos(['x1', 'x2', 'x3'], ['y1', 'y2', 'y3']),
      steps: [['A bipartite graph.', {}], ['A matching of size 3.', { e: ec('match', 'x1-y2', 'x2-y1', 'x3-y3') }], ['A vertex cover of size 3: y1, y2, x3.', { n: nc('cut', 'y1', 'y2', 'x3') }], ['Each matching edge needs its own cover vertex, so both are optimal.', {}]] },
    { term: 'Hall’s condition', text: 'A bipartite graph with parts L, R has a matching covering L iff |N(S)| ≥ |S| for every S ⊆ L. A set with |N(S)| < |S| is a short certificate of failure.',
      g: 'a x\nb x\nc x\nc y', pos: colsPos(['a', 'b', 'c'], ['x', 'y']),
      steps: [['Can every left vertex be matched?', {}], ['S = {a, b}.', { blob: [[['a', 'b'], 'sA']], n: nc('front', 'a', 'b') }], ['N(S) = {x}: one neighbour for two vertices.', { blob: [[['a', 'b'], 'sA'], [['x'], 'sB']], n: { x: 'cut' } }], ['|N(S)| = 1 < 2 = |S|: impossible.', {}]] },
    { term: 'Stable matching', text: 'A matching is <b>stable</b> if no pair prefers each other to their assigned partners (a <b>blocking pair</b>). Gale–Shapley always finds one.',
      g: 'a x\na y\nb x\nb y', pos: colsPos(['a', 'b'], ['x', 'y']),
      steps: [['a, b both prefer x to y; x prefers b, y prefers a.', {}], ['Match a–x and b–y.', { e: ec('match', 'a-x', 'b-y') }], ['b and x prefer each other: a blocking pair.', { e: { 'b-x': 'cut' }, n: nc('cut', 'b', 'x') }], ['a–y and b–x: no blocking pair. Stable.', { e: Object.assign(ec('', 'a-x', 'b-y'), ec('match', 'a-y', 'b-x')), n: nc('', 'b', 'x') }]] },
  ],
  color: [
    { term: 'Proper colouring and χ', text: 'A proper k-colouring gives each vertex one of k colours so adjacent vertices differ. The <b>chromatic number</b> χ(G) is the least such k.',
      g: 'a b\nb c\nc d\nd e\ne a', pos: ringPos(['a', 'b', 'c', 'd', 'e']),
      steps: [['The 5-cycle.', {}], ['Alternate two colours…', { n: { a: 'k0', b: 'k1', c: 'k0', d: 'k1' } }], ['…and the fifth vertex sees both.', { n: { e: 'cut' } }], ['A third colour: χ(C₅) = 3.', { n: { e: 'k2' } }]],
      gen(bg) { const c = simpleCopy(bg); if (c.error) return c; const g = c.g, S = simpleNbrSets(g), col = Array(g.nodes.length).fill(-1); const steps = [['Greedy colouring of the board’s graph, in listed order.', {}]]; g.nodes.forEach((v, i) => { const f = new Set([...S[i]].map(w => col[w])); let k = 0; while (f.has(k)) k++; col[i] = k; steps.push([`${esc(v.label)} gets colour ${k + 1}.`, { n: { [v.label]: 'k' + (k % 10) } }]); }); steps.push([`${Math.max(...col) + 1} colours: χ ≤ ${Math.max(...col) + 1}.`, {}]); return { g, pos: c.pos, steps: steps.length > 12 ? [steps[0], ...steps.slice(1, -1).filter((s, k, a) => k % Math.ceil(a.length / 10) === 0 || k === a.length - 1), steps[steps.length - 1]] : steps }; } },
    { term: 'Clique bound and Brooks', text: 'ω(G) ≤ χ(G) ≤ Δ(G) + 1. <b>Brooks:</b> χ(G) ≤ Δ(G) for connected G unless G is complete or an odd cycle.',
      g: 'a b\na c\na d\nb c\nb d\nc d\nd e', pos: { a: [60, 50], b: [60, 150], c: [150, 97], d: [215, 97], e: [275, 97] },
      steps: [['{a, b, c, d} is a clique: ω = 4.', { n: nc('front', 'a', 'b', 'c', 'd'), e: ec('tree', 'a-b', 'a-c', 'a-d', 'b-c', 'b-d', 'c-d') }], ['A clique needs distinct colours: χ ≥ 4.', { n: { a: 'k0', b: 'k1', c: 'k2', d: 'k3' } }], ['e reuses colour 1: χ = 4 = Δ + 1, since K₄ is inside.', { n: { e: 'k0' }, e: ec('', 'a-b', 'a-c', 'a-d', 'b-c', 'b-d', 'c-d') }], ['The bounds can be far apart: triangle-free graphs can need many colours.', {}]] },
    { term: 'Planar graph and faces', text: 'A graph is <b>planar</b> if it can be drawn without crossings. A plane drawing splits the plane into <b>faces</b>, including the unbounded outer face.',
      g: 'a b\nb c\nc d\nd a\na c\nb d', pos: { a: [90, 40], b: [210, 40], c: [210, 155], d: [90, 155] },
      steps: [['K₄ drawn with a crossing.', {}], ['Move the vertices…', { p: { a: [150, 22], b: [258, 168], c: [42, 168], d: [150, 112] } }], ['…no crossings: K₄ is planar.', { e: ec('tree', 'a-b', 'b-c', 'c-d', 'd-a', 'a-c', 'b-d') }], ['Four faces: three triangles inside and the outer face.', { e: ec('', 'a-b', 'b-c', 'c-d', 'd-a', 'a-c', 'b-d'), poly: [[['a', 'b', 'd'], 'fc0'], [['b', 'c', 'd'], 'fc1'], [['c', 'a', 'd'], 'fc2']] }]] },
    { term: 'Euler’s formula', text: 'Every connected plane graph satisfies n − m + f = 2. Consequence: a simple planar graph with n ≥ 3 has m ≤ 3n − 6 (and m ≤ 2n − 4 if triangle-free).',
      g: 'a b\nb c\nc a\nd a\nd b\nd c', pos: { a: [150, 22], b: [258, 168], c: [42, 168], d: [150, 112] },
      steps: [['K₄: 4 − 6 + 4 = 2.', { poly: [[['a', 'b', 'd'], 'fc0'], [['b', 'c', 'd'], 'fc1'], [['c', 'a', 'd'], 'fc2']] }], ['Contract d into a: n and m both drop by one. 3 − 5 + 4 = 2.', { p: { d: [150, 30] }, e: { 'd-a': 'hide' }, poly: [] }], ['Delete the doubled edges: m and f drop together. 3 − 3 + 2 = 2.', { e: ec('hide', 'd-b', 'd-c'), n: { d: 'hide' } }], ['Down to one vertex: 1 − 0 + 1 = 2. Each step preserved n − m + f.', {}]] },
    { term: 'Dual graph', text: 'The <b>dual</b> G* of a plane graph G has a vertex for each face and an edge crossing each edge of G. Colouring the faces of G is colouring the vertices of G*.',
      g: 'a b\nb c\nc a\nd a\nd b\nd c\nF1 F2\nF2 F3\nF3 F1\nF1 Fo\nF2 Fo\nF3 Fo', pos: { a: [150, 22], b: [250, 168], c: [50, 168], d: [150, 112], F1: [185, 90], F2: [150, 150], F3: [115, 90], Fo: [278, 30] },
      steps: [['A plane K₄.', { n: nc('hide', 'F1', 'F2', 'F3', 'Fo'), e: ec('hide', 'F1-F2', 'F2-F3', 'F3-F1', 'F1-Fo', 'F2-Fo', 'F3-Fo') }], ['Put a vertex in each face, including the outer face.', { n: nc('dualv', 'F1', 'F2', 'F3', 'Fo') }], ['Join face-vertices across every shared edge.', { e: ec('dual', 'F1-F2', 'F2-F3', 'F3-F1', 'F1-Fo', 'F2-Fo', 'F3-Fo') }], ['The dual of K₄ is K₄ again: it is self-dual.', { e: ec('faint', 'a-b', 'b-c', 'c-a', 'd-a', 'd-b', 'd-c') }]] },
  ],
  random: [
    { term: 'G(n, p)', text: 'Each of the C(n, 2) possible edges is present independently with probability p. Expected number of edges p·C(n, 2); expected degree (n − 1)p.',
      g: rgText, pos: ringPos(RG.L),
      steps: [rgStep(0.05, 'p = 0.05: {m} edges (expected 2.25).'), rgStep(0.15, 'p = 0.15: {m} edges (expected 6.75).'), rgStep(0.3, 'p = 0.3: {m} edges (expected 13.5).'), rgStep(0.5, 'p = 0.5: {m} edges (expected 22.5).')] },
    { term: 'Giant component', text: 'With p = c/n: for c < 1 all components have O(log n) vertices; for c > 1 one giant component contains a fraction S of the vertices, where S = 1 − e^(−cS).',
      g: rgText, pos: ringPos(RG.L),
      steps: [rgStep(0.05, 'Small p: tiny components.', true), rgStep(0.12, 'Components start to merge.', true), rgStep(0.2, 'One component dominates (blue).', true), rgStep(0.32, 'Most vertices are in the giant component.', true)] },
    { term: 'Clustering', text: 'The clustering coefficient (transitivity) is 3 × triangles / connected triples. In G(n, p) it is about p; real social networks are far more clustered.',
      g: 'u v\nv w\nu w\nv x', pos: { u: [70, 160], v: [150, 40], w: [230, 160], x: [270, 50] },
      steps: [['A connected triple: u–v–w, centred at v.', { e: Object.assign(ec('tree', 'u-v', 'v-w'), { 'u-w': 'hide' }) }], ['In G(n, p), u–w appears with probability p, independently.', { e: { 'u-w': 'cand' } }], ['In friendship networks a friend of a friend is likely a friend: triangles close.', { e: { 'u-w': 'tree' } }], ['Transitivity = 3·1 / 5 triples here.', {}]] },
    { term: 'Indicator variables', text: 'Write a count X as a sum of indicators, one per possible copy. Linearity of expectation gives E[X] = Σ P(copy present): for triangles, C(n, 3)·p³.',
      g: 'a b\nb c\nc a\na d\nb d\nc d', pos: ringPos(['a', 'b', 'c', 'd'], 150, 97, 66, -135),
      steps: [['K₄ has C(4, 3) = 4 possible triangles.', {}], ['X_abc = 1 if all three edges are present: probability p³.', { e: ec('cut', 'a-b', 'b-c', 'c-a') }], ['Same for abd, acd, bcd.', { e: Object.assign(ec('', 'b-c', 'c-a'), ec('cut', 'a-d', 'b-d')) }], ['E[#triangles] = 4p³, with no independence needed.', { e: ec('', 'a-b', 'a-d', 'b-d') }]] },
    { term: 'Connectivity threshold', text: 'Around p = ln n / n the last isolated vertices disappear, and at the same point G(n, p) becomes connected with high probability.',
      g: rgText, pos: ringPos(RG.L),
      steps: [rgStep(0.1, 'Isolated vertices (hollow) are common.'), rgStep(0.2, 'Fewer isolated vertices.'), rgStep(0.3, 'ln 10 / 10 ≈ 0.23: around here the last ones vanish.'), rgStep(0.4, 'No isolated vertices: connected.')] },
  ],
  dom: [
    { term: 'Dominating set', text: 'D ⊆ V <b>dominates</b> G if every vertex is in D or adjacent to a vertex of D. The domination number γ(G) is the least size of a dominating set.',
      g: 'a b\nb c\nc d\nd e\ne f\nf a', pos: ringPos(['a', 'b', 'c', 'd', 'e', 'f']),
      steps: [['Place sensors that see their own vertex and the neighbours.', {}], ['A sensor at a covers f, a, b.', { n: Object.assign({ a: 'sel' }, nc('done', 'f', 'b')) }], ['A sensor at d covers c, d, e.', { n: Object.assign({ d: 'sel' }, nc('done', 'c', 'e')) }], ['Everything is covered: γ(C₆) ≤ 2.', {}]],
      gen(bg) { const c = simpleCopy(bg); if (c.error) return c; const g = c.g; const Nc = closedNbhd(g); const dom = Array(g.nodes.length).fill(false); const steps = [['Greedy domination on the board’s graph.', {}]]; let left = g.nodes.length; while (left) { let b = -1, bc = -1; Nc.forEach((N, v) => { const k = N.filter(x => !dom[x]).length; if (k > bc) { bc = k; b = v; } }); const n = { [g.nodes[b].label]: 'sel' }; Nc[b].forEach(x => { if (!dom[x]) { dom[x] = true; left--; if (x !== b) n[g.nodes[x].label] = 'done'; } }); steps.push([`Pick ${esc(g.nodes[b].label)}: covers ${bc} new.`, { n }]); } steps.push([`${steps.length - 1} sensors.`, {}]); return { g, pos: c.pos, steps }; } },
    { term: 'Counting bound', text: 'A vertex dominates at most Δ + 1 vertices (itself and its neighbours), so γ(G) ≥ ⌈n / (Δ + 1)⌉.',
      g: 'a b\nb c\nc d\nd e\ne f\nf g', pos: rowPos(['a', 'b', 'c', 'd', 'e', 'f', 'g']),
      steps: [['The path on 7 vertices: Δ = 2.', {}], ['Each sensor covers at most 3 vertices.', { n: Object.assign({ b: 'sel' }, nc('done', 'a', 'c')) }], ['So at least ⌈7/3⌉ = 3 sensors.', { n: Object.assign({ e: 'sel', g: 'sel' }, nc('done', 'd', 'f')) }], ['And 3 suffice: γ(P₇) = 3.', {}]] },
    { term: 'Packing', text: 'A <b>packing</b> is a set of vertices with pairwise disjoint closed neighbourhoods. Each needs its own dominator, so γ(G) ≥ |P|. Packings are feasible solutions of the dual LP.',
      g: 'a b\nb c\nc d\nd e\ne f\nf g', pos: rowPos(['a', 'b', 'c', 'd', 'e', 'f', 'g']),
      steps: [['Choose a, d, g.', { n: nc('cut', 'a', 'd', 'g') }], ['Their closed neighbourhoods are disjoint.', { blob: [[['a', 'b'], 'sA'], [['c', 'd', 'e'], 'sB'], [['f', 'g'], 'sA']] }], ['No sensor can cover two of them: γ ≥ 3.', {}], ['Lower bound 3 meets the upper bound 3: optimal.', { blob: [], n: Object.assign(nc('', 'a', 'd', 'g'), nc('sel', 'b', 'e', 'g')) }]] },
    { term: 'Domination as an ILP', text: 'Minimise Σ x(v) subject to x(v) + Σ over u ∈ N(v) of x(u) ≥ 1 for every v, with x(v) ∈ {0, 1}.',
      g: 'a b\nb c\nc d\nd a\nc e', pos: { a: [60, 50], b: [60, 150], c: [160, 150], d: [160, 50], e: [260, 150] },
      steps: [['One 0/1 variable per vertex.', { t: { a: 'x=0', b: 'x=0', c: 'x=0', d: 'x=0', e: 'x=0' } }], ['Constraint at e: x(e) + x(c) ≥ 1.', { blob: [[['c', 'e'], 'sA']] }], ['x(c) = 1, x(a) = 1 satisfies every constraint.', { t: { a: 'x=1', c: 'x=1' }, n: nc('sel', 'a', 'c'), blob: [] }], ['Objective value 2 = γ.', {}]] },
    { term: 'LP relaxation', text: 'Allowing 0 ≤ x(v) ≤ 1 gives a linear program solvable in polynomial time. Its value is a lower bound on γ, sometimes strictly smaller: on C₅ it is 5/3 while γ = 2.',
      g: 'a b\nb c\nc d\nd e\ne a', pos: ringPos(['a', 'b', 'c', 'd', 'e']),
      steps: [['The 5-cycle: γ = 2.', { n: nc('sel', 'a', 'c') }], ['Fractional: x = 1/3 everywhere.', { n: nc('', 'a', 'c'), t: Object.fromEntries('abcde'.split('').map(l => [l, '1/3'])) }], ['Each closed neighbourhood sums to 1: feasible.', { blob: [[['e', 'a', 'b'], 'sA']] }], ['Value 5/3 < 2: an integrality gap.', { blob: [] }]] },
  ],
  cagt: [
    { term: 'Isomorphism classes', text: 'There are 2^C(n,2) labelled graphs on n vertices but far fewer up to isomorphism: 4 for n = 3, 11 for n = 4, 12 346 for n = 8.',
      g: 'a b\nb c\nc a', pos: ringPos(['a', 'b', 'c'], 150, 105, 60),
      steps: [['n = 3: 8 labelled graphs. No edges: one class.', { e: ec('hide', 'a-b', 'b-c', 'c-a') }], ['One edge: 3 labellings, one class.', { e: { 'a-b': '' } }], ['Two edges: 3 labellings, one class.', { e: { 'b-c': '' } }], ['Three edges: one class. Total: 4.', { e: { 'c-a': '' } }]] },
    { term: 'Vertex augmentation', text: 'Every graph on n vertices is a graph on n − 1 vertices plus one vertex joined to some subset S. Trying every G′ and S and discarding isomorphic copies lists each class once.',
      g: 'a b\nb c\nd a\nd c\nd b', pos: { a: [60, 120], b: [150, 120], c: [240, 120], d: [150, 35] },
      steps: [['G′: the path a–b–c. New vertex d.', { e: ec('hide', 'd-a', 'd-c', 'd-b'), n: { d: 'front' } }], ['S = {a}: a path on 4 vertices. New class.', { e: { 'd-a': 'hl' } }], ['S = {c}: also a path. Isomorphic: discard.', { e: { 'd-a': 'hide', 'd-c': 'cut' } }], ['S = {b}: a star. New class.', { e: { 'd-c': 'hide', 'd-b': 'hl' } }]] },
    { term: 'Counterexample vs evidence', text: 'One counterexample refutes a universal claim; any number of confirming examples proves nothing beyond them. Brooks: χ ≤ Δ except for complete graphs and odd cycles.',
      g: 'a b\na c\na d\nb c\nb d\nc d', pos: ringPos(['a', 'b', 'c', 'd'], 150, 97, 66, -135),
      steps: [['Claim: χ ≤ Δ.', {}], ['K₄: Δ = 3…', { t: { a: '3', b: '3', c: '3', d: '3' } }], ['…but χ = 4. One counterexample refutes the claim.', { n: { a: 'k0', b: 'k1', c: 'k2', d: 'k3' } }], ['Brooks: these exceptions (and odd cycles) are the only ones.', {}]] },
    { term: 'Extremal graph', text: 'ex(n, H) is the most edges an n-vertex graph can have without containing H. <b>Mantel:</b> ex(n, K₃) = ⌊n²/4⌋, attained only by the balanced complete bipartite graph.',
      g: 'a x\na y\na z\nb x\nb y\nb z\nc x\nc y\nc z\na b', pos: colsPos(['a', 'b', 'c'], ['x', 'y', 'z']),
      steps: [['K₃,₃: 9 = 6²/4 edges, no triangle.', { e: { 'a-b': 'hide' }, n: Object.assign(nc('k0', 'a', 'b', 'c'), nc('k1', 'x', 'y', 'z')) }], ['Add any edge inside a side, say a–b…', { e: { 'a-b': 'hl' } }], ['…and a triangle a–b–x appears.', { e: ec('cut', 'a-b', 'a-x', 'b-x') }], ['So 9 is the maximum for n = 6.', {}]] },
    { term: 'Simulated annealing', text: 'Explore by random local changes: always accept improvements; accept a worse move with probability e^(−ΔE/T). The temperature T decreases over time.',
      g: 'a b\nb c\nc d\nd a\na c', pos: ringPos(['a', 'b', 'c', 'd'], 150, 97, 66, -135),
      steps: [['Goal: many edges, no triangle. Energy = −edges + λ·triangles.', { e: { 'a-c': 'hide' } }], ['Try adding a–c: two triangles appear, ΔE > 0.', { e: { 'a-c': 'hl' } }], ['Hot: accept anyway with probability e^(−ΔE/T).', { e: ec('cut', 'a-c', 'a-b', 'b-c', 'c-d', 'd-a') }], ['Cold: such moves are almost always rejected.', { e: Object.assign({ 'a-c': 'hide' }, ec('', 'a-b', 'b-c', 'c-d', 'd-a')) }]] },
  ],
};
