/* ============================================================
   Pseudocode (CLRS style) per algorithm, and networkx export
   Keys are "<module>.<algo>"; frame.line indexes into the list.
   ============================================================ */
const PSEUDO = {
  'traverse.bfs': ['BFS(G, s)', '  d[v] ← ∞ for all v;  d[s] ← 0;  Q ← ⟨s⟩', '  while Q ≠ ∅', '    u ← DEQUEUE(Q)', '    for each v ∈ Adj[u]', '      if d[v] = ∞', '        d[v] ← d[u] + 1;  π[v] ← u;  ENQUEUE(Q, v)', '  edge inside one layer ⇒ odd cycle;  else layers 2-colour G'],
  'traverse.dfs': ['DFS(G)', '  for each u ∈ V: if u is white: VISIT(u)', 'VISIT(u)', '  time ← time + 1;  d[u] ← time;  colour u grey', '  for each v ∈ Adj[u]', '    if v is white: π[v] ← u;  VISIT(v)        ▹ tree edge', '    else if v is grey: back edge (cycle)', '  colour u black;  time ← time + 1;  f[u] ← time'],
  'degrees.hh': ['HAVEL-HAKIMI(d₁, …, dₙ)', '  if Σ dᵢ is odd or some dᵢ > n − 1: reject', '  repeat', '    v ← vertex with the largest residual degree k', '    if fewer than k others have residual > 0: reject', '    join v to the k next-largest; subtract 1 from each', '  until every residual is 0;  accept'],
  'degrees.swap': ['repeat k times', '  pick edges ab and cd at random (random orientation)', '  if a, b, c, d are distinct and ad, cb are not edges', '    replace ab, cd by ad, cb        ▹ every degree unchanged'],
  'degrees.bridges': ['DFS(u, parent edge)', '  disc[u] ← low[u] ← ++time', '  for each edge uv other than the parent edge', '    if v unvisited: DFS(v, uv);  low[u] ← min(low[u], low[v])', '      if low[v] > disc[u]: uv is a bridge', '      if u is not the root and low[v] ≥ disc[u]: u is a cut vertex', '    else: low[u] ← min(low[u], disc[v])     ▹ back edge', '  the root is a cut vertex ⇔ it has ≥ 2 DFS children'],
  'iso.wl': ['COLOUR-REFINEMENT(G)', '  c(v) ← 1 for every v', '  repeat', '    c′(v) ← ( c(v), {{ c(w) : w ∈ N(v) }} )   ▹ multiset', '    rename the distinct pairs by small integers', '  until the number of colours stops growing', '  different histograms ⇒ not isomorphic'],
  'iso.aut': ['refine colours until stable (1-WL)', 'backtrack: map vertices in BFS order onto vertices of equal colour', '  keep a partial map only if it preserves adjacency', 'orbits ← join v with σ(v) for every automorphism σ', 'fix a vertex with the largest orbit; repeat until only id remains'],
  'mst.kruskal': ['KRUSKAL(G)', '  sort E by weight;  MAKE-SET(v) for every v', '  for each edge uv in sorted order', '    if FIND(u) ≠ FIND(v)', '      T ← T ∪ {uv};  UNION(u, v)', '    else reject uv (it would close a cycle)', '  return T'],
  'mst.prim': ['PRIM(G, r)', '  T ← {r}', '  while some edge leaves T', '    uv ← lightest edge with u ∈ T, v ∉ T', '    T ← T ∪ {v};  add uv', '  return the tree'],
  'sp.dijkstra': ['DIJKSTRA(G, s)', '  d[v] ← ∞ for all v;  d[s] ← 0;  Q ← V', '  while Q ≠ ∅', '    u ← EXTRACT-MIN(Q)          ▹ u is settled', '    for each v ∈ Adj[u]', '      if d[u] + w(u, v) < d[v]', '        d[v] ← d[u] + w(u, v);  π[v] ← u', '  check: d(v) ≤ d(u) + w(u, v) on every edge'],
  'sp.bf': ['BELLMAN-FORD(G, s)', '  d[v] ← ∞;  d[s] ← 0', '  repeat n − 1 times', '    for each edge (u, v)', '      if d[u] + w(u, v) < d[v]: d[v] ← d[u] + w(u, v);  π[v] ← u', '  if some edge can still be relaxed: negative cycle'],
  'sp.hops': null,
  'sp.astar': ['A*(G, s, t, h)    ▹ h(v) ≤ true distance to t', '  g[s] ← 0;  open ← {s}', '  u ← vertex in open with least g[u] + h(u);  stop if u = t', '  move u to closed', '  for each v ∈ Adj[u]: if g[u] + w(u, v) < g[v]: g[v] ← g[u] + w(u, v); π[v] ← u', '  return the path s → t along π'],
  'sp.fw': ['D ← W   (0 on the diagonal, ∞ where there is no edge)', 'for k ← 1 to n', '  for i ← 1 to n', '    for j ← 1 to n', '      D[i][j] ← min(D[i][j], D[i][k] + D[k][j])', 'negative cycle ⇔ some D[v][v] < 0'],
  'route.euler': ['if some vertex has odd degree', '  pair the odd vertices with least total distance; duplicate those paths', 'stack ← ⟨start⟩;  circuit ← ⟨⟩', 'while stack ≠ ∅', '  v ← top of stack', '  if v has an unused edge vw: mark it used; push w', '  else: pop v; prepend v to circuit', 'return circuit'],
  'route.ham': ['EXTEND(path)', '  if |path| = n: success if last(path) ~ first(path)', '  for each neighbour v of last(path) with v ∉ path', '    EXTEND(path + v)', '  backtrack'],
  'route.tsp': ['nearest neighbour: walk to the closest unvisited vertex', 'T ← minimum spanning tree            ▹ OPT ≥ w(T)', 'double tree: preorder walk of T, skip repeats   ▹ ≤ 2·OPT', 'Christofides: M ← min-weight perfect matching on odd vertices of T', '  Euler circuit of T + M, skip repeats   ▹ ≤ 1.5·OPT', 'Held–Karp: C(S, j) = min over i of C(S ∖ {j}, i) + d(i, j)'],
  'flow.ek': ['EDMONDS-KARP(G, s, t)', '  f ← 0', '  while the residual network G_f has an s–t path', '    p ← a shortest such path (BFS);  b ← min residual capacity on p', '    push b along p   (forward arcs +b, backward arcs −b)', '  S ← vertices reachable from s in G_f;  (S, V ∖ S) is a minimum cut'],
  'match.kuhn': ['for each left vertex u', '  AUGMENT(u)  with an empty visited set', 'AUGMENT(u)', '  for each neighbour v of u not yet visited', '    mark v;  if v is free or AUGMENT(match[v])', '      match u with v;  return true', '  return false', 'Z ← reachable from free left vertices by alternating paths;  C ← (L ∖ Z) ∪ (R ∩ Z)'],
  'match.hk': ['repeat   ▹ one phase', '  BFS from all free left vertices along alternating paths → layers', '  DFS: a maximal set of vertex-disjoint shortest augmenting paths', '  augment along all of them', 'until no augmenting path exists;  a König cover certifies |M|'],
  'match.hung': ['u ← 0, v ← 0     ▹ keep c(i, j) − u(i) − v(j) ≥ 0', 'for each row i', '  grow an alternating tree from i on tight edges; if stuck, shift potentials by δ', '  augment along the tight path to a free column', 'certificate: Σu + Σv = cost of the assignment'],
  'match.gs': ['while some proposer p is free and has someone left to ask', '  r ← highest on p’s list not yet asked', '  if r is free: r holds p', '  else if r prefers p to her current p′: r holds p;  p′ becomes free', '  else: r rejects p', 'return the matching (stable, proposer-optimal)'],
  'color.planar': ['split G into blocks;  G planar ⇔ every block planar', 'H ← a cycle;  faces ← {inside, outside}', 'repeat until every edge is embedded', '  embed a path of a fragment with fewest admissible faces (none ⇒ not planar)', 'not planar: delete edges while still non-planar → Kuratowski subgraph', 'plane drawing: n − m + f = 2', 'dual: a vertex per face, an edge across every edge'],
  'color.greedy': ['for each vertex v in the chosen order', '  c(v) ← smallest colour not used by a coloured neighbour', 'return c          ▹ at most Δ + 1 colours'],
  'color.dsatur': ['while some vertex is uncoloured', '  v ← uncoloured vertex seeing the most distinct colours (ties: higher degree)', '  c(v) ← smallest colour not used by its neighbours'],
  'color.exact': ['ω ← size of a maximum clique         ▹ χ ≥ ω', 'for k ← ω, ω + 1, …', '  if backtracking finds a proper k-colouring: return χ = k'],
  'random.gnp': ['give every pair uv an independent uniform r(uv)', 'G(n, p) = pairs with r(uv) < p     ▹ raising p only adds edges', 'track components with union–find as p grows'],
  'random.real': ['read the airport network (n = 546, m = 2 781)', 'G(n, m): choose m of the C(n, 2) pairs uniformly at random', 'compare degrees, triangles, distances'],
  'dom.greedy': ['D ← ∅', 'while some vertex is undominated', '  v ← vertex whose closed neighbourhood covers most undominated vertices', '  D ← D ∪ {v}', 'return D        ▹ at most (1 + ln(Δ+1))·γ'],
  'dom.exact': ['u ← first undominated vertex', '  some vertex of N[u] must be in D: branch on each', '  prune when |D| + ⌈undominated / (Δ+1)⌉ ≥ best'],
  'cagt.conj': ['generate all graphs on n vertices up to isomorphism', 'for each graph G: compute the invariants', '  if the statement is false for G: record a counterexample'],
  'cagt.gen': ['for each graph G′ on n − 1 vertices', '  for each subset S of V(G′)', '    G ← G′ plus a new vertex joined to S', '    if G ≅ a kept graph: discard;  else keep G'],
  'cagt.sa': ['G ← empty graph;  T ← T₀', 'repeat', '  toggle a random pair uv;  ΔE ← change in (−edges + λ·violations)', '  accept if ΔE ≤ 0, else with probability e^(−ΔE/T)', '  T ← T · cooling', 'return the best graph with no violations'],
};
PSEUDO['sp.hops'] = PSEUDO['traverse.bfs'];

/* ---------- networkx export ---------- */
function pyStr(s) { return JSON.stringify(String(s)); }
function pyGraph(g, name = 'G') {
  const lab = i => pyStr(g.nodes[i].label);
  const out = [`${name} = nx.${g.directed ? 'DiGraph' : 'Graph'}()`];
  out.push(`${name}.add_nodes_from([${g.nodes.map((v, i) => lab(i)).join(', ')}])  # in the lab's order`);
  const weighted = g.weighted || g.edges.some(e => e.w !== 1);
  const chunks = []; for (let k = 0; k < g.edges.length; k += 6) chunks.push(g.edges.slice(k, k + 6).map(e => weighted ? `(${lab(e.u)}, ${lab(e.v)}, ${e.w})` : `(${lab(e.u)}, ${lab(e.v)})`).join(', '));
  if (g.edges.length) out.push(`${name}.add_${weighted ? 'weighted_' : ''}edges_from([\n    ${chunks.join(',\n    ')},\n])`);
  return out.join('\n');
}
function partGraph(g, part, suffix = '') {
  const idx = g.nodes.map((v, i) => i).filter(i => (g.nodes[i].part || 0) === part); const pos = new Map(idx.map((v, k) => [v, k]));
  return { directed: g.directed, weighted: g.weighted, nodes: idx.map(i => Object.assign({}, g.nodes[i], { label: g.nodes[i].label + suffix })), edges: g.edges.filter(e => pos.has(e.u) && pos.has(e.v)).map(e => ({ u: pos.get(e.u), v: pos.get(e.v), w: e.w })) };
}
function unionGraph(g) { if ((g.parts || 1) < 2) return g; const out = { directed: g.directed, weighted: g.weighted, nodes: g.nodes.map(v => Object.assign({}, v, { label: v.part ? v.label + '_' + (v.part + 1) : v.label })), edges: g.edges }; return out; }
function pythonSnippet(modKey, algoKey, g, P) {
  const L = i => (g && g.nodes[i]) ? pyStr(g.nodes[i].label) : '0';
  const head = 'import networkx as nx\n\n';
  const G = g ? pyGraph(unionGraph(g)) + '\n\n' : '';
  const k = modKey + '.' + algoKey;
  switch (k) {
    case 'traverse.bfs': case 'sp.hops': return head + G + `layers = dict(enumerate(nx.bfs_layers(G, ${L(P.source)})))\nprint(layers)\nprint("bipartite:", nx.is_bipartite(G))`;
    case 'traverse.dfs': return head + G + `print(list(nx.dfs_edges(G, ${L(P.source)})))\nif G.is_directed() and nx.is_directed_acyclic_graph(G):\n    print("topological order:", list(nx.topological_sort(G)))`;
    case 'degrees.hh': return head + `seq = [${P.seq.split(/[\s,;]+/).filter(Boolean).join(', ')}]\nprint("graphical:", nx.is_graphical(seq, method="hh"))\nif nx.is_graphical(seq):\n    H = nx.havel_hakimi_graph(seq)\n    print(sorted(H.edges()))`;
    case 'degrees.swap': return head + G + `nx.double_edge_swap(G, nswap=${P.k}, max_tries=1000, seed=${P.seed})\nprint(sorted(d for _, d in G.degree()), "triangles:", sum(nx.triangles(G).values()) // 3)`;
    case 'degrees.bridges': return head + G + `print("bridges:", list(nx.bridges(G)))\nprint("cut vertices:", list(nx.articulation_points(G)))`;
    case 'iso.wl': return head + ((g && (g.parts || 1) > 1) ? pyGraph(partGraph(g, 0), 'G1') + '\n' + pyGraph(partGraph(g, 1), 'G2') + '\n\n' : G + 'G1 = G2 = G  # put the second graph after a line --- in the lab\n') + `print("WL hashes equal:", nx.weisfeiler_lehman_graph_hash(G1) == nx.weisfeiler_lehman_graph_hash(G2))\nprint("isomorphic:", nx.is_isomorphic(G1, G2))`;
    case 'iso.aut': return head + G + `from networkx.algorithms.isomorphism import GraphMatcher\nauts = list(GraphMatcher(G, G).isomorphisms_iter())\nprint("|Aut(G)| =", len(auts))`;
    case 'mst.kruskal': case 'mst.prim': case 'mst.race': return head + G + `T = nx.minimum_spanning_tree(G, algorithm="${algoKey === 'prim' ? 'prim' : 'kruskal'}")\nprint(sorted(T.edges(data="weight")), "total:", T.size(weight="weight"))`;
    case 'sp.dijkstra': return head + G + `dist, paths = nx.single_source_dijkstra(G, ${L(P.source)})\nprint(dist)`;
    case 'sp.bf': return head + G + `if nx.negative_edge_cycle(G):\n    print("negative cycle:", nx.find_negative_cycle(G, ${L(P.source)}))\nelse:\n    print(nx.single_source_bellman_ford_path_length(G, ${L(P.source)}))`;
    case 'sp.astar': { const pos = g ? `pos = {${g.nodes.map(v => `${pyStr(v.label)}: (${v.x.toFixed(0)}, ${v.y.toFixed(0)})`).join(', ')}}\n` : ''; return head + G + pos + `from math import dist\nalpha = min(w / dist(pos[u], pos[v]) for u, v, w in G.edges(data="weight"))\nh = lambda u, v: alpha * dist(pos[u], pos[v])\nprint(nx.astar_path(G, ${L(P.source)}, ${L(P.target)}, heuristic=h), nx.astar_path_length(G, ${L(P.source)}, ${L(P.target)}, heuristic=h))`; }
    case 'sp.fw': case 'sp.race': return head + G + `D = nx.floyd_warshall_numpy(G)\nprint(list(G.nodes()))\nprint(D)`;
    case 'route.euler': return head + G + `if nx.is_eulerian(G):\n    print(list(nx.eulerian_circuit(G)))\nelse:\n    odd = [v for v, d in G.degree() if d % 2]\n    print("odd vertices:", odd)\n    # nx.eulerize ignores weights; for the weighted postman pair odd vertices by\n    # min_weight_matching on shortest-path distances, as the lab does.\n    D = dict(nx.all_pairs_dijkstra_path_length(G))\n    K = nx.Graph(); K.add_weighted_edges_from((a, b, D[a][b]) for i, a in enumerate(odd) for b in odd[i+1:])\n    print("pairing:", nx.min_weight_matching(K))`;
    case 'route.ham': return head + G + `def hamilton_cycle(G, s):\n    n, path = G.number_of_nodes(), [s]\n    def extend():\n        if len(path) == n:\n            return G.has_edge(path[-1], s)\n        for v in G[path[-1]]:\n            if v not in path:\n                path.append(v)\n                if extend():\n                    return True\n                path.pop()\n        return False\n    return path if extend() else None\n\nprint(hamilton_cycle(G, ${L(P.source)}))`;
    case 'route.tsp': return head + G + `from networkx.algorithms import approximation as approx\nfor name, method in [("christofides", approx.christofides), ("greedy", approx.greedy_tsp)]:\n    tour = approx.traveling_salesman_problem(G, cycle=True, method=method)\n    length = sum(nx.dijkstra_path_length(G, a, b) for a, b in zip(tour, tour[1:]))\n    print(name, tour, length)`;
    case 'flow.ek': case 'flow.race': return head + G + `from networkx.algorithms.flow import edmonds_karp\nvalue, flow = nx.maximum_flow(G, ${L(P.source)}, ${L(P.sink)}, capacity="weight", flow_func=edmonds_karp)\ncut_value, (S, T) = nx.minimum_cut(G, ${L(P.source)}, ${L(P.sink)}, capacity="weight")\nprint(value, cut_value, sorted(S))`;
    case 'match.kuhn': case 'match.hk': case 'match.race': return head + G + `top = {v for v, c in nx.bipartite.color(G).items() if c == 0}\nM = nx.bipartite.hopcroft_karp_matching(G, top_nodes=top)\nC = nx.bipartite.to_vertex_cover(G, M, top_nodes=top)\nprint(len(M) // 2, "matched;  cover:", sorted(C))`;
    case 'match.hung': { let pc; try { pc = parseCost(P.cost); } catch (e) { pc = null; } return 'import numpy as np\nfrom scipy.optimize import linear_sum_assignment\n\n' + (pc ? `rows = ${JSON.stringify(pc.rows)}\ncols = ${JSON.stringify(pc.cols)}\nC = np.array(${JSON.stringify(pc.C)})\n` : 'C = np.array([[...]])\n') + `r, c = linear_sum_assignment(C)\nprint([(rows[i], cols[j]) for i, j in zip(r, c)], C[r, c].sum())`; }
    case 'match.gs': return `def gale_shapley(P, R):\n    """P, R: dict name -> preference list. Proposers in P."""\n    rank = {r: {p: i for i, p in enumerate(R[r])} for r in R}\n    nxt, holds, free = {p: 0 for p in P}, {}, list(P)\n    while free:\n        p = free.pop(0)\n        if nxt[p] >= len(P[p]):\n            continue\n        r = P[p][nxt[p]]; nxt[p] += 1\n        cur = holds.get(r)\n        if p not in rank[r]:\n            free.append(p)\n        elif cur is None or rank[r][p] < rank[r][cur]:\n            holds[r] = p\n            if cur is not None:\n                free.append(cur)\n        else:\n            free.append(p)\n    return {p: r for r, p in holds.items()}\n\n# fill in from the preference box:\nP = {"a": ["x", "y", "z"], "b": ["y", "x", "z"], "c": ["x", "y", "z"]}\nR = {"x": ["b", "a", "c"], "y": ["a", "b", "c"], "z": ["a", "b", "c"]}\nprint(gale_shapley(P, R))`;
    case 'color.planar': return head + G + `planar, emb = nx.check_planarity(G, counterexample=True)\nif planar:\n    seen, faces = set(), 0\n    for u, v in emb.edges():\n        if (u, v) not in seen:\n            emb.traverse_face(u, v, mark_half_edges=seen)\n            faces += 1\n    print("planar;", faces, "faces")\nelse:\n    print("Kuratowski subgraph:", sorted(emb.edges()))`;
    case 'color.greedy': { const st = { listed: 'lambda G, colors: list(G)', largest: '"largest_first"', smallestlast: '"smallest_last"', random: '"random_sequential"' }[P.order] || '"largest_first"'; return head + G + `c = nx.greedy_color(G, strategy=${st})\nprint(max(c.values()) + 1, "colours", c)`; }
    case 'color.dsatur': return head + G + `c = nx.greedy_color(G, strategy="DSATUR")\nprint(max(c.values()) + 1, "colours", c)`;
    case 'color.exact': return head + G + `from itertools import product\ndef chromatic_number(G):\n    V = list(G)\n    for k in range(1, len(V) + 1):\n        col = {}\n        def place(i):\n            if i == len(V):\n                return True\n            for c in range(min(k, max(col.values(), default=-1) + 2)):\n                if all(col.get(w) != c for w in G[V[i]]):\n                    col[V[i]] = c\n                    if place(i + 1):\n                        return True\n                    del col[V[i]]\n            return False\n        if place(0):\n            return k, col\n\nprint(chromatic_number(G))\nprint("clique number:", max(len(c) for c in nx.find_cliques(G)))`;
    case 'random.gnp': return head + `n, c, seed = ${P.n}, 3.0, ${P.seed}\nG = nx.gnp_random_graph(n, c / (n - 1), seed=seed)\ngiant = max(nx.connected_components(G), key=len)\nprint(len(giant) / n, nx.transitivity(G), sum(nx.triangles(G).values()) // 3)`;
    case 'random.real': return head + `G = nx.read_edgelist("data/openflights/openflights_usa.edges.gz")  # from the course repo\nn, m = G.number_of_nodes(), G.number_of_edges()\nR = nx.gnm_random_graph(n, m, seed=1)\nfor name, H in [("airports", G), ("G(n, m)", R)]:\n    print(name, nx.transitivity(H), max(d for _, d in H.degree()))`;
    case 'dom.greedy': case 'dom.exact': return head + G + `print("a dominating set (not necessarily minimum):", nx.dominating_set(G))\n\n# exact: the domination ILP with SciPy's MILP solver (SciPy >= 1.9)\nimport numpy as np\nfrom scipy.optimize import milp, LinearConstraint, Bounds\nV = list(G); idx = {v: i for i, v in enumerate(V)}\nA = np.zeros((len(V), len(V)))\nfor v in V:\n    A[idx[v], idx[v]] = 1          # x(v) + sum of x(u) over neighbours u >= 1\n    for u in G[v]:\n        A[idx[v], idx[u]] = 1\nfor integral in (True, False):\n    res = milp(c=np.ones(len(V)), constraints=LinearConstraint(A, lb=1), integrality=np.ones(len(V)) if integral else None, bounds=Bounds(0, 1))\n    print("ILP gamma =" if integral else "LP bound  =", round(res.fun, 3), [V[i] for i in range(len(V)) if res.x[i] > 0.5] if integral else "")`;
    case 'cagt.conj': return head + `# nx.graph_atlas_g() lists every graph on at most 7 vertices up to isomorphism\nn = ${Math.min(7, P.n)}\nbad = []\nfor G in nx.graph_atlas_g():\n    if G.number_of_nodes() != n or not nx.is_connected(G):\n        continue\n    chi = max(nx.greedy_color(G, "DSATUR").values()) + 1  # upper bound only! replace by an exact routine\n    dmax = max(d for _, d in G.degree())\n    if not chi <= dmax:\n        bad.append(nx.to_graph6_bytes(G, header=False))\nprint(len(bad), bad)`;
    case 'cagt.gen': return `# The lab's method, for small n. For real work use nauty:  geng -c ${P.n}  (connected graphs)\nimport networkx as nx\nfrom itertools import combinations\n\ndef graphs_of_order(n):\n    if n == 1:\n        return [nx.empty_graph(1)]\n    out = []\n    for H in graphs_of_order(n - 1):\n        for k in range(n):\n            for S in combinations(range(n - 1), k):\n                G = H.copy(); G.add_node(n - 1); G.add_edges_from((n - 1, s) for s in S)\n                if not any(nx.is_isomorphic(G, K) for K in out):\n                    out.append(G)\n    return out\n\nprint([len(graphs_of_order(n)) for n in range(1, ${Math.min(6, P.n + 1)})])`;
    case 'cagt.sa': return `import math, random\nimport networkx as nx\n\ndef anneal(n=${P.n}, steps=${P.iters}, lam=1.6, seed=${P.seed}):\n    rnd = random.Random(seed); G = nx.empty_graph(n); best = None\n    viol = lambda: sum(nx.triangles(G).values()) // 3   # triangle count\n    for t in range(steps):\n        T = 1.5 * (0.02) ** (t / steps)\n        u, v = rnd.sample(range(n), 2)\n        before = -G.number_of_edges() + lam * viol()\n        G.remove_edge(u, v) if G.has_edge(u, v) else G.add_edge(u, v)\n        dE = -G.number_of_edges() + lam * viol() - before\n        if dE > 0 and rnd.random() >= math.exp(-dE / T):\n            G.remove_edge(u, v) if G.has_edge(u, v) else G.add_edge(u, v)\n        if viol() == 0 and (best is None or G.number_of_edges() > best.number_of_edges()):\n            best = G.copy()\n    return best\n\nB = anneal(); print(B.number_of_edges(), "edges; Mantel bound", ${P.n} ** 2 // 4)`;
    default: return head + G + '# no export for this view';
  }
}
